name: "infra.deploy.securityCenter"
description: "Deploy Security Center"
inputs:
  variables:
    description: "Variables"
    required: true
  target-ring:
    description: "Target Ring"
    required: true
runs:
  using: "composite"
  steps:
    - uses: azure/arm-deploy@v1
      name: Enable Azure Security Center
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        # Figure out paths
        template: ${{ github.workspace }}/ARM/AzureSecurityCenter/deploy.json
        parameters: ${{ github.workspace }}/Parameters/AzureSecurityCenter/parameters.json scope=${{ fromJSON(inputs.variables).SubscriptionScope }} workspaceId=${{ fromJSON(inputs.variables).LogAWorkspaceId }}
        deploymentMode: 'Incremental'
        deploymentName: deployAzureSecurityCenter-${{ github.run_id }}

    - name: Enable Defender on Resources
      uses: Azure/powershell@v1
      with:
        # Specify the Az PowerShell script here.
        inlineScript: ${{ github.workspace }}/Scripts/Set-AzureDefenderPricingTier.ps1 -Resources ${{ fromJSON(inputs.variables).Resources }}
        azPSVersion: "latest"