name: "app.deploy.dnc.api.aks"
description: "Deploy Dnc Api"
inputs:
  variables:
    description: "Variables"
    required: true
  target-ring:
    description: "Target Ring"
    required: true
    
runs:
  using: "composite"
  steps:

    - name: Update Node AKS Backend policy
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        $fileList = @(
          "Parameters\APIManagement\APIs\DncAks\apim-products.template.json",
          "Parameters\APIManagement\APIs\DncAks\apim-productAPIs.template.json",
          "Parameters\APIManagement\APIs\DncAks\Dnc-API-Microservice.api.template.json"
        )

        $replacementList = @{
          "[[DncCertName]]" = "${{ fromJSON(inputs.variables).DncCertName }}"
          "[[DncApiApimUrl]]" = "${{ fromJSON(inputs.variables).DncApiAksBackendUrl }}"
          "[[Suffix]]" = "${{ fromJSON(inputs.variables).DncAksApimSuffix }}"
          "[[AuthCert]]" = '<authentication-certificate certificate-id=\"Acna-Cert\" />'
        }

        ${{ github.workspace }}/Scripts/Update-TemplateText.ps1 -FileList $fileList -ReplacementList $replacementList

    - name: Create APIM Product
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/DncAks/apim-products.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/DncAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployApiManagementApi-${{ github.run_id }}

    - name: Create DncApp.Api Aks APIM API
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/DncAks/Dnc-API-Microservice.api.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/DncAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployDncAppApi-${{ github.run_id }}

    - name: Associate DncApp.Api APIM APIs to APIM Product
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/DncAks/apim-productAPIs.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/DncAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployAssociateDnc2Api-${{ github.run_id }}