name: "gateway.deploy.gwAksAPIM"
description: "Deploy Application Gateway"
inputs:
  target-ring:
    required: true  
  variables:
    description: "Variables"
    required: true
  parameter-file:
    type: string
    description: ""
    required: true
  webDnsName:
    type: string
    description: ""
    required: true
  kvName:
    type: string
    description: ""
    required: true

runs:
  using: "composite"
  steps:

    - name: Update Gateway Parameters File
      uses: ./.github/actions/Common/updateParamFile
      with:
        parameter-file: ${{ github.workspace }}/Parameters/ApplicationGateway/parametersAksAPIM.json
        variables-file: ${{ github.workspace }}/.github/Variables/Variables-${{ inputs.target-ring }}.env


    - name: Update AKS App Gateway Parameters File For Additional Values
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        $ClientSecret = Get-AzKeyVaultSecret -Name clientsecret -VaultName ${{ fromJSON(inputs.variables).KeyVaultName }}  -AsPlainText
        $SessionSecret = Get-AzKeyVaultSecret -Name sessionsecret -VaultName ${{ fromJSON(inputs.variables).KeyVaultName }}  -AsPlainText
        $Authority = Get-AzKeyVaultSecret -Name authority -VaultName ${{ fromJSON(inputs.variables).KeyVaultName }}  -AsPlainText
        $fileList = @( "Parameters/ApplicationGateway/parametersAks.json" )
        $replacementList = @{
          "[[WebAppApplicationGatewayName]]" = "${{fromJSON(inputs.variables).WebAppApplicationGatewayName}}"
          "[[VoteWebDnsName]]" = "${{fromJSON(inputs.variables).VoteWebDnsName}}"
          "[[NodeApiDnsName]]" = "${{fromJSON(inputs.variables).NodeApiDnsName}}"
          "[[DncApiDnsName]]" = "${{fromJSON(inputs.variables).DncApiDnsName}}"
          "[[DncWebDnsName]]" = "${{fromJSON(inputs.variables).DncWebDnsName}}"       
        }
        ${{ github.workspace }}/Scripts/Update-TemplateText.ps1 -FileList $fileList -ReplacementList $replacementList       

    - uses: azure/arm-deploy@v1
      name: Create App Gateway
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/ARM/ApplicationGateway/deploy.json
        parameters: ${{ github.workspace }}/Parameters/ApplicationGateway/parametersAksAPIM.json
        deploymentMode: 'Incremental'
        deploymentName: deployApplicationGateway-${{ github.run_id }}        