name: "gateway.deploy.aks"
description: "Deploy Application Gateway"
inputs:
  variables:
    description: "Variables"
    required: true
  target-ring:
    description: "Target Ring"
    required: true
runs:
  using: "composite"
  steps:

  - name: Update AKS App Gateway Parameters File
    uses: ./.github/actions/Common/updateParamFile
    with:
      parameter-file: ${{ github.workspace }}/Parameters/ApplicationGateway/parametersAks.json
      variables-file: ${{ github.workspace }}/.github/Variables/Variables-${{ inputs.target-ring }}.env

  - name: Update AKS App Gateway Parameters File For Additional Values
    shell: pwsh
    working-directory: ${{ github.workspace }}
    run: |
      $KvVersionKey = (Get-AzKeyVaultSecret -Name ${{ fromJSON(inputs.variables).SecretName }} -VaultName ${{ fromJSON(inputs.variables).KeyVaultName }}).Version
      Write-Host "##vso[task.setvariable variable=KvVersionKey;isOutput=true]$KvVersionKey"
      Write-Host "KvVersionKey: $KvVersionKey"
      $fileList = @( "Parameters/ApplicationGateway/parametersAks.json" )
      $replacementList = @{
        "[[KvVersionKey]]" = $KvVersionKey
      }
      ${{ github.workspace }}/Scripts/Update-TemplateText.ps1 -FileList $fileList -ReplacementList $replacementList       

  - uses: azure/arm-deploy@v1
    name: Create App Gateway
    with:
      scope: resourcegroup
      region: ${{fromJSON(inputs.variables).TargetRegion }}
      resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
      template: ${{ github.workspace }}/ARM/ApplicationGateway/deploy.json
      parameters: ${{ github.workspace }}/Parameters/ApplicationGateway/parametersAks.json
      deploymentMode: 'Incremental'
      deploymentName: deployApplicationGateway-${{ github.run_id }}     