name: "app.deploy.telemetry.api.aks"
description: "Deploy Telemetry Api"
inputs:
  variables:
    description: "Variables"
    required: true
  target-ring:
    description: "Target Ring"
    required: true
    
runs:
  using: "composite"
  steps:

    - name: Update Telemetry AKS Backend policy
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        $fileList = @(
        "Parameters\APIManagement\APIs\TelmsAks\apim-products.template.json",
        "Parameters\APIManagement\APIs\TelmsAks\apim-productAPIs.template.json",
        "Parameters\APIManagement\APIs\TelmsAks\Telms-API-Microservice.api.template.json"
        )

        $replacementList = @{
          "[[TelmsDnsName]]" = "${{ fromJSON(inputs.variables).TelmsDnsName }}"
          "[[Suffix]]" = "${{ fromJSON(inputs.variables).TelmsName }}"
        }

        ${{ github.workspace }}/Scripts/Update-TemplateText.ps1 -FileList $fileList -ReplacementList $replacementList

    - name: Update Telms AKS APIM parameters with APIM service name
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: ${{ github.workspace }}/Scripts/Update-ApimParameter.ps1 -VariablesFile ${{ github.workspace }}/.github/Variables/Variables-${{ fromJSON(inputs.variables).parametersPath }}.env -ParametersFile ${{ github.workspace }}/${{fromJSON(inputs.variables).parametersPath}}/APIManagement/APIs/TelmsAks/apim-parameters.json


    - name: Create APIM Product
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/TelmsAks/apim-products.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/TelmsAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployApiTelemetryApi-${{ github.run_id }}

    - name: Create Telemetry.Api Aks APIM API
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/TelmsAks/Telms-API-Microservice.api.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/TelmsAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployDncAppApi-${{ github.run_id }}

    - name: Associate Telemetry.Api APIM APIs to APIM Product
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/TelmsAks/apim-productAPIs.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/TelmsAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployAssociateTelemetryApi-${{ github.run_id }}