name: "infra.deploy.appConfiguration"
description: "Deploy App Configuration Service"
inputs:
  variables:
    description: "Variables"
    required: true
  target-ring:
    description: "Target Ring"
    required: true
runs:
  using: "composite"
  steps:

    - name: Update Private DNS Zones Parameters File
      uses: ./.github/actions/Common/updateParamFile
      with:
        parameter-file: ${{ github.workspace }}/Parameters/PrivateDnsZones/parameters.json
        variables-file: ${{ github.workspace }}/.github/Variables/Variables-${{ inputs.target-ring }}.env

    - uses: azure/arm-deploy@v1
      name: Deploy Azure App Configuration Private DNS Zone
      id: AacPrivateDnsZone
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/ARM/PrivateDnsZones/deploy.json
        parameters: ${{ github.workspace }}/Parameters/PrivateDnsZones/parameters.json privateDnsZoneName=${{ fromJSON(inputs.variables).AACPrivateDnsZoneName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployAacPrivateDnsZones-${{ github.run_id }}

    - uses: azure/arm-deploy@v1
      name: Create Azure App Configuration
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/ARM/AppConfiguration/deploy.json
        parameters: ${{ github.workspace }}/Parameters/AppConfiguration/parameters.json aacName=${{ fromJSON(inputs.variables).AACName }} cuaId=${{ fromJSON(inputs.variables).cuaId }}
        deploymentMode: 'Incremental'
        deploymentName: deployAzureAppConfiguration-${{ github.run_id }}

    - uses: azure/arm-deploy@v1
      name: Deploy Azure App Configuration Private Endpoints
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/ARM/PrivateEndpoints/deploy.json
        parameters: ${{ github.workspace }}/Parameters/PrivateEndpoints/parameters.json privateEndpointName=${{ fromJSON(inputs.variables).AACPrivateEndPointName }} targetSubnetId=${{ fromJSON(inputs.variables).PrivateEndpointTargetSubnetId }} privateDNSId=${{ fromJSON(inputs.variables).AACPrivateEndpointPrivateDNSId }} serviceResourceId=${{ fromJSON(inputs.variables).AACPrivateEndpointServiceResourceId }} groupId="[\"configurationStores\"]" cuaId=${{ fromJSON(inputs.variables).cuaId }}
        deploymentMode: 'Incremental'
        deploymentName: deployAppConfigurationPrivateEndpoints-${{ github.run_id }}