
name: "restartAksDeployment"
description: "Restart AKS Deployment"
inputs:
  variables:
    description: "Variables"
    required: true   
  deployment-name:
    required: true    
  replicas:
    required: true        

runs:
  using: "composite"
  steps:
    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3

    - name: Set AKS context with AZ CLI
      shell: bash
      run: |
        az aks get-credentials --name ${{ fromJSON(inputs.variables).AksName }} --resource-group ${{ fromJSON(inputs.variables).TargetResourceGroupCore }}  --admin --overwrite-existing

    - name: Restarting Deployment
      shell: bash
      run: |
        kubectl scale --replicas=0 deployments/${{inputs.deployment-name}} 
        kubectl scale --replicas=${{inputs.replicas}} deployments/${{inputs.deployment-name}}