name: "platform.deploy.dapr"
description: "Deploy DAPR"
inputs:
  variables:
    description: "Variables"
    required: true
  target-ring:
    description: "Target Ring"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      name: Checkout Repo

    - name: Update DAPR install script
      uses: ./.github/actions/Common/updateParamFile
      with:
        parameter-file: ${{ github.workspace }}/Scripts/Dapr/setup-dapr.sh
        variables-file: ${{ github.workspace }}/.github/Variables/Variables-${{ inputs.target-ring }}.env  

    - name: Configure and Install DAPR using HELM
      shell: bash
      run: | 
          chmod +x ${{ github.workspace }}/Scripts/Dapr/setup-dapr.sh
          ${{ github.workspace }}/Scripts/Dapr/setup-dapr.sh
      env: 
        STAGE: "dev"