name: "app.deploy.node.api.aks"
description: "Deploy Node Api"
inputs:
  variables:
    description: "Variables"
    required: true
  target-ring:
    description: "Target Ring"
    required: true
    
runs:
  using: "composite"
  steps:

    - name: Update Kube Config and App Service Deployment Ingress Files
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        $fileList = @(
          "Parameters\APIManagement\APIs\NodeAks\apim-products.template.json",
          "Parameters\APIManagement\APIs\NodeAks\apim-productAPIs.template.json",
          "Parameters\APIManagement\APIs\NodeAks\Node-API-Microservice.api.template.json"
        )

        $replacementList = @{
          "[[NodeCertName]]" = "${{ fromJSON(inputs.variables).NodeCertName }}"
          "[[NodeApiApimUrl]]" = "${{ fromJSON(inputs.variables).NodeApiAksBackendUrl }}"
          "[[Suffix]]" = "${{ fromJSON(inputs.variables).NodeAksApimSuffix }}"
          "[[AuthCert]]" = '<authentication-certificate certificate-id=\"Acna-Cert\" />'
        }

        ${{ github.workspace }}/Scripts/Update-TemplateText.ps1 -FileList $fileList -ReplacementList $replacementList

    - name: Create APIM Product
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/NodeAks/apim-products.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/NodeAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployApiManagementApi-${{ github.run_id }}

    - name: Create Node AKS API
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/NodeAks/Node-API-Microservice.api.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/NodeAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployNodeAppApi-${{ github.run_id }}

    - name: Associate Node AKS API to Node Product
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        template: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/NodeAks/apim-productAPIs.template.json
        parameters: ${{ github.workspace }}/${{ fromJSON(inputs.variables).parametersPath }}/APIManagement/APIs/NodeAks/apim-parameters.json ApimServiceName=${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
        deploymentMode: 'Incremental'
        deploymentName: deployAssociateNode2Api-${{ github.run_id }}