name: Hello World
description: 'Echoes "Hello, World!" using a bash'
author: Jim Davis
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: |
        echo "$Hello {{ inputs.who-to-greet }}"
      shell: bash
