name: "infra.deploy.bastion"
description: "Deploy Bastion"
inputs:
  variables:
    description: "Variables"
    required: true
  target-ring:
    description: "Target Ring"
    required: true
runs:
  using: "composite"
  steps:
    - uses: azure/arm-deploy@v1
      name: Create AzureBastion
      with:
        scope: resourcegroup
        region: ${{fromJSON(inputs.variables).TargetRegion }}
        resourceGroupName: ${{fromJSON(inputs.variables).TargetResourceGroupCore }}
        # Figure out paths
        template: ${{ github.workspace }}/ARM/AzureBastion/deploy.json
        parameters: ${{ github.workspace }}/Parameters/AzureBastion/parameters.json azureBastionName=${{ fromJSON(inputs.variables).azureBastionName }} cuaId=${{ fromJSON(inputs.variables).cuaId }} azureBastionPipName=${{ fromJSON(inputs.variables).azureBastionName }} vNetId=${{ fromJSON(inputs.variables).bastionVNet }}
        deploymentMode: 'Incremental'
        deploymentName: deployBastion-${{ github.run_id }}