name: Build Apps

on:
  workflow_call:
    inputs:
      target-ring:
        required: true
        type: string 
      variables:
        required: true
        type: string  

permissions:
  id-token: write
  contents: read

jobs:
   build-apps:
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    name: build apps
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: ./.github/actions/Build/app.build.scan
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/Build/app.build.nodeapi
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/Build/app.build.vote
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/Build/app.build.dnc
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}          