name: Deploy Infra Ring

on:
  workflow_call:
    inputs:
      target-ring:
        required: true
        type: string 
      variables:
        required: true
        type: string    
        
permissions:
  id-token: write
  contents: read

jobs:
  DeployRingInfra_0:
    name: DeployRingInfra_0
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - uses: actions/checkout@v2
        name: Checkout Repo

      - name: Sample Task
        uses: ./.github/actions/Common/helloWorld
        with:
          who-to-greet: 'world'
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}      

  DeployRingInfra_1:
    name: DeployRingInfra_1
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_0]
    steps:       
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}    

      - uses: actions/checkout@v2
        name: Checkout Repo

      - name: Sample Task
        uses: ./.github/actions/Common/helloWorld
        with:
          who-to-greet: 'world'
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

  DeployRingInfra_2:
    name: DeployRingInfra_2
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_0]
    if: fromJSON(inputs.variables).DeploymentType == 'AKS'
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true

      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - uses: actions/checkout@v2
        name: Checkout Repo

      - name: Sample Task
        uses: ./.github/actions/Common/helloWorld
        with:
          who-to-greet: 'world'
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

  DeployRingInfra_3:
    name: DeployRingInfra_3
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_2]
    if: ${{ fromJSON(inputs.variables).DeploymentType == 'AKS' || fromJSON(inputs.variables).DeploymentType == 'All' }}
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true

      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - uses: actions/checkout@v2
        name: Checkout Repo

      - name: Sample Task
        uses: ./.github/actions/Common/helloWorld
        with:
          who-to-greet: 'world'
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

  DeployRingInfra_4:
    name: DeployRingInfra_4
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_2]
    if: fromJSON(inputs.variables).DeployAPIM == 'true'
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true

      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}    

      - name: Sample Task
        uses: ./.github/actions/Common/helloWorld
        with:
          who-to-greet: 'world'
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}
     

  DeployRingInfra_Last:
    name: DeployRingInfra_Last
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_0, DeployRingInfra_1, DeployRingInfra_2, DeployRingInfra_3, DeployRingInfra_4]
    if: ${{ always() }}
    steps:  
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true

      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}       

      - uses: actions/checkout@v2
        name: Checkout Repo

      - name: Sample Task
        uses: ./.github/actions/Common/helloWorld
        with:
          who-to-greet: 'world'
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}