name: Deploy Telemetry

on:
  workflow_call:
    inputs:
      target-ring:
        required: true
        type: string 
      variables:
        required: true
        type: string  

permissions:
  id-token: write
  contents: read

jobs:
  Deploy-Telemtry:
    if: fromJSON(inputs.variables).DeployTelemetryMicroservice
    name: Deploy Telemetry
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).ClientId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: ./.github/actions/Telemetry/telemetry.deploy.database
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/Telemetry/telemetry.deploy.ingress-ms
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/AppDeploy/app.deploy.telemetry.api.aks
        if: fromJSON(inputs.variables).DeployAPIM == 'true'
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - name: Deploy Telemetry Cert to APIM 
        if: fromJSON(inputs.variables).DeploymentType == 'AKS' && fromJSON(inputs.variables).DeployAPIM == 'true'
        uses: ./.github/actions/Common/importApimCert
        with:
          keyvault-name:  ${{ fromJSON(inputs.variables).KeyVaultName }} 
          resource-group: ${{ fromJSON(inputs.variables).TargetResourceGroupCore }}  
          cert-name: ${{ fromJSON(inputs.variables).TelmsAuthCertName }} 
          apim-service-name: ${{ fromJSON(inputs.variables).ApiManagementServiceName }} 
          selfsigned: ${{ fromJSON(inputs.variables).SelfSignedCertificate }} 
          dns-name: ${{ fromJSON(inputs.variables).TelmsDnsName }} 
