name: Deploy Core Infra

on:
  workflow_call:
    inputs:
      target-ring:
        required: true
        type: string 
      variables:
        required: true
        type: string  

permissions:
  id-token: write
  contents: read

jobs:
  deploy-core-infra:
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    name: Deploy Core Infra
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo

      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
          
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          # creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - name: Sample Task
        uses: ./.github/actions/Common/helloWorld
        with:
          who-to-greet: 'world'