name: Deploy Infra Ring

on:
  workflow_call:
    inputs:
      target-ring:
        required: true
        type: string 
      variables:
        required: true
        type: string    
        
permissions:
  id-token: write
  contents: read

jobs:
  DeployRingInfra_0:
    name: Base Azure Services
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: ./.github/actions/InfraRing/infra.deploy.appConfiguration
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/InfraRing/infra.deploy.keyvault
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/InfraRing/infra.deploy.containerRegistry
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/InfraRing/infra.deploy.logAnalyticsAppInsight
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}           

  DeployRingInfra_1:
    name: Bastion, Jumpbox, Storage
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_0]
    steps:       
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}    
      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: ./.github/actions/InfraRing/infra.deploy.bastion
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/InfraRing/infra.deploy.jumpbox
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      # TODO: ADD BACK IN WHEN STORAGE IS NEEDED
      # - uses: ./.github/actions/InfraRing/infra.deploy.storage
      #   with:
      #     variables: ${{ inputs.variables }}
      #     target-ring: ${{ inputs.target-ring }}

  DeployRingInfra_2:
    name: AKS Prereqs
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_0]
    if: fromJSON(inputs.variables).DeploymentType == 'AKS'
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - uses: actions/checkout@v2
        name: Checkout Repo

      # DEPLOYS PREREQ ITEMS FOR APP GATEWAY (NEEDS TO COMPLETE BEFORE APP GATEWAY)
      - uses: ./.github/actions/InfraRing/infra.deploy.gwpre
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

  DeployRingInfra_3:
    name: AKS Infra
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_2]
    if: ${{ fromJSON(inputs.variables).DeploymentType == 'AKS' || fromJSON(inputs.variables).DeploymentType == 'All' }}
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}

      - uses: actions/checkout@v2
        name: Checkout Repo

      # DEPLOY AKS 
      # SETTING ENV PARAMETER TO DEV WILL USE PARAMETER WITHOUT ZONES
      - uses: ./.github/actions/InfraRing/infra.deploy.aks.ingress
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}
          env: 'DEV'

  DeployRingInfra_4:
    name: APIM
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_2]
    if: fromJSON(inputs.variables).DeployAPIM == 'true'
    steps:
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}    
      - uses: actions/checkout@v2
        name: Checkout Repo

      # DEPLOY APIM
      - uses: ./.github/actions/InfraRing/infra.deploy.apim
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}
      

  DeployRingInfra_Last:
    name: Final Infra
    runs-on: ${{fromJSON(inputs.variables).RunnerLabel }}
    needs: [DeployRingInfra_0, DeployRingInfra_1, DeployRingInfra_2, DeployRingInfra_3, DeployRingInfra_4]
    if: ${{ always() }}
    steps:  
      # LOGIN AZ POWERSHELL
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}
          enable-AzPSSession: true
      # LOGIN AZ CLI
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{fromJSON(inputs.variables).RunnerServicePrincipalId }}","clientSecret":"${{ secrets.AZURE_CREDENTIALS }}","subscriptionId":"${{fromJSON(inputs.variables).SubscriptionId }}","tenantId":"${{fromJSON(inputs.variables).TenantId }}"}'
          # client-id: ${{fromJSON(inputs.variables).RunnerServicePrincipalId }}
          # tenant-id: ${{fromJSON(inputs.variables).TenantId }}
          # subscription-id: ${{fromJSON(inputs.variables).SubscriptionId }}            
      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: ./.github/actions/InfraRing/infra.deploy.workbooks
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}

      - uses: ./.github/actions/InfraRing/infra.deploy.securityCenter
        with:
          variables: ${{ inputs.variables }}
          target-ring: ${{ inputs.target-ring }}